### ISSUE TITLE
Tips | Meeting a potential client

### ISSUE THREAD

**Issue by iteles** [dwyl/ateam-master-reference#12]
- [ ] Buy a watch/pedometer with a vibrating alarm, set it for 5 minutes before the meeting is set to finish - looking at your watch will come across as being disinterested
- [ ] Be generous - offer advice if you think it will add value _whether or not_ you end up working together (I don't mean do half a day of work for free, but good tips that people who might not have managed an app build before might benefit from for example); at best you transmit that you genuinely care about things going well for your client (which you _genuinely should_) and at worst you've just made both your client and their future developers' lives easier
- [ ] Don't forget this person probably knows very little about you and what makes you special even though _you_ know everything there is to know about you already :wink:
- [ ] Time-Budget-Scope triangle
- More to come.

**Comment by Cleop** [comment]
I am creating a README on this topic to include the above points and more I observed when we took a project scoping call.
