### ISSUE TITLE
Keeping a sprint demo under control

### ISSUE THREAD

**Issue by iteles** [dwyl/ateam-master-reference#5]
So far in our experience, this seems to be portion of interacting with the client that is more prone to issues.

Need to delineate some thoughts on this and keeping the situation under control.

**Comment by iteles** [comment]
Jargon (e.g. A question on why something has been added as a toggle instead of something else 'a common design pattern' doesn't mean much to a lot of people - frame it in terms of familiarity to the user

**Comment by Cleop** [comment]
I've added a point regarding technical language / jargon in #22, however I'm not sure if this covers everything that you'd originally envisaged @iteles? 

#22 also adds other points for helping to keep a sprint demo under control which may cover some of the other thoughts you may have been having but that weren't yet recorded here! Feel free to take a look and let me know if you're happy for this issue to be closed once it's merged...

**Comment by Cleop** [comment]
@iteles any thoughts on the above? Would you be happy to close this?

**Comment by iteles** [comment]
@Cleop This is great start, thanks!
