### ISSUE TITLE
Internal feedback!

### ISSUE THREAD

**Issue by iteles** [dwyl/ateam-master-reference#7]
We need to be giving continuous feedback, sure, but also we need a way to gather and give the more overarching 'not every day' feedback from everyone in the team

**Comment by Cleop** [comment]
Is this issue a repeat of: https://github.com/dwyl/hq/issues/182 ? Which seems to have more content added to it. If so, @iteles would you be able to close this one?

**Comment by nelsonic** [comment]
@Cleop pretty much.
